/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 heart_shaped_porta.glb --transform 
Files: heart_shaped_porta.glb [5.16MB] > E:\DS\WebD\React\reactthreefibre\reactthree5\public\models\heart_shaped_porta-transformed.glb [216.92KB] (96%)
Author: Creater (https://sketchfab.com/7f5609904fe14de59b74533836ad9b)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/a-heart-shaped-portal-fbx-8b72ca62d0cd4bc1bf19bae008fcd444
Title: A_Heart_Shaped_Portal_fbx
*/
import Snowfall from './Snowfall.jsx'
import React from 'react'
import { useGLTF } from '@react-three/drei'

export default function Portal(props) {
  const { nodes, materials } = useGLTF('/models/heart_shaped_porta-transformed.glb')
  return (
    <group {...props} dispose={null}>
      <Snowfall  count={1000}/>
      <mesh castShadow receiveShadow geometry={nodes.temp_Material001_0.geometry} material={materials['Material.001']} />
    </group>
  )
}

useGLTF.preload('/models/heart_shaped_porta-transformed.glb')
