/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 the_little_witch.glb --transform 
Files: the_little_witch.glb [4.23MB] > E:\DS\WebD\React\reactthreefibre\reactthree5\public\models\the_little_witch-transformed.glb [423.12KB] (90%)
Author: Antropik (https://sketchfab.com/Antropik)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/the-little-witch-9fcc764e98ba47a5b2127d878bf360d8
Title: The little Witch
*/

import React from 'react'
import { useGraph } from '@react-three/fiber'
import { useGLTF } from '@react-three/drei'
import { SkeletonUtils } from 'three-stdlib'

export default function Witch(props) {
  const { scene } = useGLTF('/models/the_little_witch-transformed.glb')
  const clone = React.useMemo(() => SkeletonUtils.clone(scene), [scene])
  const { nodes, materials } = useGraph(clone)

 
  return (
    <group {...props} dispose={null}>
      <primitive object={nodes.GLTF_created_0_rootJoint} />
      <skinnedMesh castShadow geometry={nodes.Object_7.geometry} material={materials.Material} skeleton={nodes.Object_7.skeleton} scale={1.128} />
      <skinnedMesh castShadow geometry={nodes.Object_8.geometry} material={materials['Material.001']} skeleton={nodes.Object_8.skeleton} scale={1.128} />
      <skinnedMesh castShadow geometry={nodes.Object_9.geometry} material={materials['Material.002']} skeleton={nodes.Object_9.skeleton} scale={1.128} />
      <skinnedMesh castShadow geometry={nodes.Object_11.geometry} material={materials.Material} skeleton={nodes.Object_11.skeleton} scale={1.128} />
      <skinnedMesh castShadow geometry={nodes.Object_12.geometry} material={materials['Material.001']} skeleton={nodes.Object_12.skeleton} scale={1.128} />
      <skinnedMesh castShadow geometry={nodes.Object_14.geometry} material={materials.Material} skeleton={nodes.Object_14.skeleton} scale={1.128} />
      <skinnedMesh castShadow geometry={nodes.Object_15.geometry} material={materials['Material.001']} skeleton={nodes.Object_15.skeleton} scale={1.128} />
      <skinnedMesh castShadow geometry={nodes.Object_17.geometry} material={materials.Material} skeleton={nodes.Object_17.skeleton} scale={1.128} />
      <skinnedMesh castShadow geometry={nodes.Object_18.geometry} material={materials['Material.001']} skeleton={nodes.Object_18.skeleton} scale={1.128} />
      <skinnedMesh castShadow geometry={nodes.Object_20.geometry} material={materials.Material} skeleton={nodes.Object_20.skeleton} scale={1.128} />
      <skinnedMesh castShadow geometry={nodes.Object_21.geometry} material={materials['Material.001']} skeleton={nodes.Object_21.skeleton} scale={1.128} />
      <skinnedMesh castShadow geometry={nodes.Object_22.geometry} material={materials['Material.003']} skeleton={nodes.Object_22.skeleton} scale={1.128} />
    </group>
  )
}

useGLTF.preload('/models/the_little_witch-transformed.glb')
